[workspace]

members = [
    "secp256kfun",
    "schnorr_fun",
    "ecdsa_fun",
    "sigma_fun",
    "arithmetic_macros",
    "vrf_fun"
]
resolver = "2"

[workspace.dependencies]
bincode = { version = "2",  default-features = false, features = ["derive"] }
