edition = "2021"
condense_wildcard_suffixes = true
format_macro_matchers = true
imports_granularity="Crate"
use_field_init_shorthand = true
format_code_in_doc_comments = true
overflow_delimited_expr = true
